spring:
  config:
    import: optional:secrets.yml
  datasource:
    url: jdbc:mysql://localhost:3306/it_bootcamp
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    root: info
  file:
    name: it-bootcamp.log
    path: /